import QtQuick 2.15

Item {
    function getColor(shortName) {
        const alias = getAlias(shortName);
        return collectiondata.metadata[alias].color
            ?? collectiondata.metadata['default'].color;
    }

    function getVendorYear(shortName) {
        const alias = getAlias(shortName);
        const vendor = collectiondata.metadata[alias].vendor ?? '';
        const year = collectiondata.metadata[alias].year ?? '';

        return [vendor, year]
            .filter(v => { return v !== '' })
            .join(' • ');
    }
	
	function getYear(shortName) {
        const alias = getAlias(shortName);
		return collectiondata.metadata[alias].year ?? '';
	}
	
	function getSummary(shortName) {
        const alias = getAlias(shortName);
        return collectiondata.metadata[alias].summary ?? '';
	}

    function getImage(shortName) {
        const alias = getAlias(shortName);
        if (alias === 'default') return shortName;
        return collectiondata.metadata[alias].image ?? alias;
    }

    function getAlias(shortName) {
        if (aliases[shortName] !== undefined) return aliases[shortName];
        if (metadata[shortName] !== undefined) return shortName;
        return 'default'
    }

    property var aliases: {
        '2600': 'atari2600',
        '5200': 'atari5200',
        '7800': 'atari7800',
        'jaguar': 'atarijaguar',
        'lynx': 'atarilynx',
        'cd-i': 'cdi',
        'msdos': 'dos',
        'dc': 'dreamcast',
        'fc': 'famicom',
        'fba': 'fbneo',
        'fbn': 'fbneo',
        'gc': 'gamecube',
        'gameboy': 'gb',
        'gameboyadvance': 'gba',
        'gameboycolor': 'gbc',
        'md': 'genesis',
        'megadrive': 'genesis',
        'gameandwatch': 'gw',
        'gamewatch': 'gw',
        'sms': 'mastersystem',
        'msx2': 'msx',
        'msx2+': 'msx',
        'aes': 'neogeo',
        'neogeoaes': 'neogeo',
        'pcenginecd': 'pcecd',
        'pce': 'pcengine',
        'pico-8': 'pico8',
        'ps1': 'psx',
		'ps vita': 'vita',
        'mega32x': 'sega32x',
        'megacd': 'segacd',
        'superfamicom': 'sfc',
        'superfc': 'sfc',
        'sg-1000': 'sg1000',
        'supernes': 'snes',
        'turbografx16': 'tg16',
        'tg16cd': 'tgcd',
        'turbografx16cd': 'tgcd',
        'vb': 'vboy',
        'virtualboy': 'vboy',
        'wonderswan': 'wswan',
        'wonderswanc': 'wswanc',
        'wonderswancolor': 'wswanc',
        'x68k': 'x68000',

        // launchbox shortnames
        '3do interactive multiplayer': '3do',
        'nintendo 3ds': '3ds',
        'commodore amiga': 'amiga',
        'amstrad cpc': 'amstradcpc',
        'apple ii': 'apple2',
        'atari 2600': 'atari2600',
        'atari 5200': 'atari5200',
        'atari 7800': 'atari7800',
        'atari jaguar': 'atarijaguar',
        'atari lynx': 'atarilynx',
        'atari st': 'atarist',
        'sammy atomiswave': 'atomiswave',
        'commodore 64': 'c64',
        'capcom cps1': 'cps1',
        'capcom cps2': 'cps2',
        'capcom cps3': 'cps3',
        'sega dreamcast': 'dreamcast',
        'final burn alpha': 'fbneo',
        'final burn neo': 'fbneo',
        'nintendo famicom disk system': 'fds',
        'nintendo gamecube': 'gamecube',
        'sega game gear': 'gamegear',
        'nintendo game boy': 'gb',
        'nintendo game boy advance': 'gba',
        'nintendo game boy color': 'gbc',
        'sega genesis': 'genesis',
        'sega mega drive': 'genesis',
        'mattel intellivision': 'intellivision',
        'sega master system': 'mastersystem',
        'microsoft msx': 'msx',
        'microsoft msx2': 'msx',
        'nintendo 64': 'n64',
        'nintendo ds': 'nds',
        'nintendo entertainment system': 'nes',
        'snk neo geo aes': 'neogeo',
        'snk neo geo mvs': 'neogeo',
        'snk neo geo cd': 'neogeocd',
        'snk neo geo pocket': 'ngp',
        'snk neo geo pocket color': 'ngpc',
        'nec pc-fx': 'pcfx',
        'sony playstation 2': 'ps2',
        'sony psp': 'psp',
        'sony playstation': 'psx',
		'sony ps vita': 'vita',
        'sega saturn': 'saturn',
        'sega 32x': 'sega32x',
        'sega cd': 'segacd',
        'sega sg-1000': 'sg1000',
        'super nintendo entertainment system': 'snes',
        'pc engine supergrafx': 'supergrafx',
        'nec turbografx-16': 'tg16',
        'gce vectrex': 'vectrex',
        'nintendo wii': 'wii',
        'nintendo wii u': 'wiiu',
        'sinclair zx spectrum': 'zxspectrum',
    }

    property var metadata: {
        '3do': { color: '#d0a73f', vendor: 'The 3DO Company', year: '1993', summary: 'The 3DO Interactive Multiplayer, often called simply 3DO, is a video game console originally produced by Panasonic in 1993. Further renditions of the hardware were released in 1994 by Sanyo and Goldstar. The consoles were manufactured according to specifications created by The 3DO Company, and were originally designed by Dave Needle and RJ Mical of New Technology Group. The system was conceived by entrepreneur and Electronic Arts founder Trip Hawkins. Despite a highly promoted launch (including being named Time magazines "1994 Product of the Year") and a host of cutting-edge technologies, the 3DOs high price (US$699.95 at launch), limited third-party developer support, and an over-saturated console market prevented the system from achieving success comparable to competitors Sega and Nintendo. This console was released in North America on October 4, 1993, Japan on March 20, 1994 and in Europe in 1994.' },
        '3ds': { color: '#697583', vendor: 'Nintendo', year: '2011', summary: 'The autostereoscopic device is able to project stereoscopic 3D effects without the use of 3D glasses or any additional accessories. The Nintendo 3DS features backward compatibility with Nintendo DS series software, including Nintendo DSi software. Announcing the device in March 2010, Nintendo officially unveiled it at E3 2010, with the company inviting attendees to use demonstration units. The console succeeds the Nintendo DS series of handheld systems and competes with Sony PlayStation Vita handheld console.' },
        'allgames': { color: '#292463' },
        'amiga': { color: '#3870c5', vendor: 'Commodore', year: '1985', summary: 'The Amiga is a family of personal computers marketed by Commodore in the 1980s and 1990s. The first model was launched in 1985 as a high-end home computer and became popular for its graphical, audio and multi-tasking abilities. The Amiga provided a significant upgrade from 8-bit computers, such as the Commodore 64, and the platform quickly grew in popularity among computer enthusiasts. The best selling model, the Amiga 500, was introduced in 1987 and became the leading home computer of the late 1980s and early 1990s in much of Western Europe. In North America success was more modest. The Amiga went on to sell approximately six million units. Second generation Amiga systems (A1200 and A4000) were released in 1992. However, poor marketing and failure to repeat the technological advances of the first systems meant that the Amiga quickly lost its market share to competing platforms, such as the fourth generation game consoles, Apple Macintosh and IBM PC compatibles.' },
        'android': { color: '#2ec781', vendor: 'Google', year: '2008', summary: 'Android is a Linux-based operating system designed primarily for touchscreen mobile devices such as smartphones and tablet computers. Initially developed by Android, Inc., which Google backed financially and later bought in 2005, Android was unveiled in 2007 along with the founding of the Open Handset Alliance: a consortium of hardware, software, and telecommunication companies devoted to advancing open standards for mobile devices. The first Android-powered phone was sold in October 2008.' },
        'arcade': { color: '#5D60B9', summary: 'An arcade game is a coin-operated (also bill-operated or card-operated) entertainment machine, usually installed in public businesses such as restaurants, public houses, and video arcades. Arcade video games are often composed of short levels, intuitive control mechanisms and a rising difficulty. This is the main concept of an arcade video game in which the player is essentially obliged to pay to maintain the play.' },
        'atari2600': { color: '#b92e35', vendor: 'Atari', year: '1977', summary: 'The Atari 2600 is a video game console released in October 1977 by Atari, Inc. It is credited with popularizing the use of microprocessor-based hardware and cartridges containing game code, instead of having non-microprocessor dedicated hardware with all games built in. The first game console to use this format was the Fairchild Channel F; however, the Atari 2600 receives credit for making the plug-in concept popular among the game-playing public. The console was originally sold as the Atari VCS, for Video Computer System. Following the release of the Atari 5200, in 1982, the VCS was renamed "Atari 2600", after the units Atari part number, CX2600. The 2600 was typically bundled with two joystick controllers, a conjoined pair of paddle controllers, and a cartridge game—initially Combat and later Pac-Man. The Atari 2600 was wildly successful, and during much of the 1980s, "Atari" was a synonym for this model in mainstream media and, by extension, for video games in general.' },
        'atari5200': { color: '#40599c', vendor: 'Atari', year: '1982', summary: 'The Atari 5200 SuperSystem, commonly known as the Atari 5200, is a video game console that was introduced in 1982 by Atari Inc. as a higher end complementary console for the popular Atari 2600. The 5200 was created to compete with the Intellivision, but wound up more directly competing with the ColecoVision shortly after its release. The 5200 was based on Atari Inc.s existing 400/800 computers and the internal hardware was almost identical, although software was not directly compatible between the two systems. The 5200s controllers feature an analog joystick and a numeric keypad along with start, pause and reset buttons. The 360-degree non-centering joystick was touted as offering more control than the four-position joystick controller offered with the Atari 2600.' },
        'atari7800': { color: '#2f7bc7', vendor: 'Atari', year: '1986', summary: 'The Atari 7800 ProSystem, or simply the Atari 7800, is a video game console re-released by Atari Corporation in January 1986. The original release had occurred two years earlier under Atari Inc. The 7800 had originally been designed to replace Atari Inc.s Atari 5200 in 1984, but was temporarily shelved due to the sale of the company after the video game crash. In January 1986, the 7800 was again released and would compete that year with the Nintendo Entertainment System and the Sega Master System. It had simple digital joysticks; it was almost fully backward-compatible with the Atari 2600(and was the first console to have backward compatibility without the use of additional modules); and it was considered affordable at a price of US$140.' },
        'atarijaguar': { color: '#cf3d3e', vendor: 'Atari', year: '1993', summary: 'The Atari Jaguar is a video game console that was released by Atari Corporation in 1993. It was the last to be marketed under the Atari brand until the release of the Atari Flashback in 2004. It was designed to surpass the Mega Drive/Genesis, Super Nintendo Entertainment System, and the Panasonic 3DO in processing power. Although launched one year earlier, it was eventually in competition with the Sega Saturn, the Sony PlayStation, and other consoles that made up the fifth generation of video game consoles. The console was first released in New York City and San Francisco on November 23, 1993, and the rest of the country in early 1994. Although it was promoted as the first 64-bit gaming system, the Jaguar proved to be a commercial failure and prompted Atari to leave the home video game console market. Despite its commercial failure, the Jaguar has a dedicated fan base that produces homebrew games for it.' },
        'atarilynx': { color: '#e49838', vendor: 'Atari', year: '1989', summary: 'The Atari Lynx is a 16-bit handheld game console that was released by Atari Corporation in September 1989. The Lynx holds the distinction of being the worlds first handheld electronic game with a color LCD. The system is also notable for its forward-looking features, advanced graphics, and ambidextrous layout. As part of the fourth generation of gaming, the Lynx competed with Nintendos Game Boy (released just a month earlier), the Sega Game Gear and NECs TurboExpress, both released the following year.' },
        'atomiswave': { color: '#30ae6e', vendor: 'Sammy', year: '2003', summary: 'The Atomiswave is a custom arcade system board and cabinet from Sammy Corporation. It is based on Segas Dreamcast console, Sega sharing similarities with the NAOMI, as far as it uses interchangeable game cartridges, as well as a removable module for changing the control scheme (including dual joysticks, dual light guns and a steering wheel), but unlike the NAOMI, the Atomiswave does not feature expanded RAM compared to the Dreamcast. With the retirement of the aging Neo Geo MVS system, SNK Playmore chose the Atomiswave as its next system to develop games for.[ In a contract with Sammy, SNK Playmore agreed to develop five games for the Atomiswave system. Metal Slug 6 was SNK Playmores fifth game for the Atomiswave, after which SNK moved on to a Taito Type X2 arcade board. Since its discontinuation, the Atomiswave library has received homebrew conversions to the Dreamcast.' },
        'c64': { color: '#0959b2', vendor: 'Commodore', year: '1982', summary: 'The Commodore 64 is an 8-bit home computer introduced by Commodore International in January 1982. Volume production started in the spring of 1982, with machines being released on to the market in August at a price of US$595. Preceded by the Commodore VIC-20 and Commodore PET machines, the C64 features 64 kilobytes (65,536 bytes) of RAM, hence the name, and had favourable sound and graphical specifications when compared to well-known contemporary systems such as the Apple II, particularly as the price was well below that demanded by Apple. It is commonly known as the C64 or C=64 (after the graphic logo on the case) and occasionally as the CBM 64 (for Commodore Business Machines), or VIC-64.' },
        'cdi': { color: '#c171a4', vendor: 'Philips', year: '1990', summary: 'The Philips CD-i (Compact Disc Interactive) is an interactive multimedia CD player developed and marketed by Royal Philips Electronics N.V. This category of device was created to provide more functionality than an audio CD player or game console, but at a lower price than a personal computer with CD-ROM drive at the time. The cost savings were due to the lack of a hard drive, floppy drive, keyboard, mouse, monitor (a standard television was used), and less operating system software. In addition to games, educational and multimedia reference titles were produced, such as interactive encyclopedias, museum tours, etc. before public Internet access was widespread. Competitors included the Tandy VIS and Commodore CDTV. CD-i also refers to the multimedia Compact Disc standard used by the CD-i console, also known as Green Book, which was developed by Philips and Sony (not to be confused with MMCD, the pre-DVD format also co-developed by Philips and Sony). Work on the CD-i began in 1984 and it was first publicly announced in 1986.' },
        'colecovision': { color: '#de5b3f', vendor: 'Coleco', year: '1982', summary: 'The ColecoVision is Coleco Industries second generation home video game console which was released in August 1982. The ColecoVision offered arcade-quality graphics and gaming style, and the means to expand the systems basic hardware. Released with a catalog of 12 launch titles, with an additional ten games announced for 1982, approximately 145 titles in total were published as ROM cartridges for the system between 1982 and 1984.' },
        'cps1': { color: '#025836', vendor: 'Capcom', year: '1988', summary: 'The CP System (CPS for short and retroactively known as CPS-1) is an arcade system board developed by Capcom that ran game software stored on removable daughterboards. More than two dozen arcade titles were released for CPS-1, before Capcom shifted game development over to its successor, the CP System II. Among the 33 titles released for the original CP System include Street Fighter II: The World Warrior and its first two follow-ups, Street Fighter II: Champion Edition and Street Fighter II: Hyper Fighting.' },
        'cps2': { color: '#049728', vendor: 'Capcom', year: '1993', summary: 'The CP System II or CPS-2 is an arcade system board that Capcom first used in 1993 for Super Street Fighter II. It was the successor to their previous CP System and Capcom Power System Changer arcade hardware and was succeeded by the CP System III hardware in 1996, of which the CPS-2 would outlive by over four years. The arcade system had new releases for it until the end of 2003, ending with Hyper Street Fighter II.' },
        'cps3': { color: '#258ed1', vendor: 'Capcom', year: '1996', summary: 'The CP System III or CPS-3 is an arcade system board that was first used by Capcom in 1996 with the arcade game Red Earth. It was the second successor to the CP System arcade hardware, following the CP System II. It would be the last proprietary system board Capcom would produce before moving on to the Dreamcast-based Naomi platform.' },
        'default': { color: '#194492' },
        'dos': { color: '#2d62c1', vendor: 'Microsoft', year: '1981', summary: 'MS-DOS (acronym for Microsoft Disk Operating System, also known as Microsoft DOS) is an operating system for x86-based personal computers mostly developed by Microsoft. MS-DOS was the main operating system for IBM PC compatibles during the 1980s, from which point it was gradually superseded by operating systems offering a graphical user interface (GUI), in various generations of the graphical Microsoft Windows operating system.' },
        'dreamcast': { color: '#4d7dd7', vendor: 'Sega', year: '1998', summary: 'The Dreamcast is a 128-bit video game console which was released by Sega in late 1998 in Japan and from September 1999 in other territories. It was the first entry in the sixth generation of video game consoles, preceding Sonys PlayStation 2, Microsofts Xbox and the Nintendo GameCube. Dreamcast sales were positive during launch, but because of the strong pressure from rival PlayStation 2, Dreamcast sales decreased, and Sega finally discontinued the Dreamcast in March 2001 and withdrew entirely from the console hardware business, making it the companys final console.' },
        'famicom': { color: '#ba3141', vendor: 'Nintendo', year: '1983', summary: 'The Nintendo Entertainment System (also abbreviated as NES or simply called Nintendo) is an 8-bit video game console that was released by Nintendo in North America during 1985, in Europe during 1986 and Australia in 1987. In most of Asia, including Japan (where it was first launched in 1983), China, Vietnam, Singapore, the Middle East and Hong Kong, it was released as the Family Computer, commonly shortened as either the romanized contraction Famicom, or abbreviated to FC. In South Korea, it was known as the Hyundai Comboy, and was distributed by Hynix which then was known as Hyundai Electronics. As the best-selling gaming console of its time, the NES helped revitalize the US video game industry following the video game crash of 1983, and set the standard for subsequent consoles of its generation. With the NES, Nintendo introduced a now-standard business model of licensing third-party developers, authorizing them to produce and distribute software for Nintendos platform.' },
        'favorites': { color: '#82cdea' },
        'fbneo': { color: '#3b2dd4', image: 'arcade' },
        'fds': { color: '#191a49', vendor: 'Nintendo', year: '1986', summary: 'The Family Disk System was released on February 21, 1986 by Nintendo as a peripheral for the Nintendo Family Computer console in Japan. It uses proprietary floppy disks (called "Disk Cards") for data storage. The Disk Systems Disk Cards are somewhat proprietary 71 mm × 76 mm (2.8x3 in) 56K-per-side double-sided floppy. These "Disk Cards," as they are officially called, were a slight modification of Mitsumis "Quick Disk" 89 mm 2.8 in square disk format which is used in a handful of Japanese computers and various synthesizer keyboards, along with a few word processors. Some of the QuickDisk drives even made it into devices in Europe and North America, though they are somewhat rare. Mitsumi already had close relations with Nintendo, as it manufactured the Famicom and NES consoles, and possibly other Nintendo hardware.'},
        'gamecube': { color: '#9682f0', vendor: 'Nintendo', year: '2001', summary: 'The Nintendo GameCube was the first Nintendo console to use optical discs as its primary storage medium, after several aborted projects from Nintendo and its partners to utilize optical-based storage media. In contrast with the GameCubes contemporary competitors, Sonys PlayStation 2, Segas Dreamcast and Microsofts Xbox, the GameCube uses miniDVD-based discs instead of full-size DVDs. Partially as a result of this, it does not have the DVD-Video playback functionality of these systems, nor the audio CD playback ability of other consoles that use full-size optical discs. In addition, the GameCube introduced a variety of connectivity options to Nintendo consoles, and was the fourth Nintendo console, after the Nintendo 64DD, Famicom Modem and Satellaview, to support online play officially, via the Nintendo GameCube Broadband Adapter and Modem Adapter (sold separately). It also enabled connectivity to the Game Boy Advance to access exclusive features of certain games or to use the portable system as a controller for the Game Boy Player.' },
        'gamegear': { color: '#366fb1', vendor: 'Sega', year: '1990', summary: 'The Sega Game Gear was Segas first handheld game console. It was the third commercially available color handheld console, after the Atari Lynx and the TurboExpress. Work began on the console in 1989 under the codename "Project Mercury", following Segas policy at the time of codenaming their systems after planets. The system was released in Japan on October 6, 1990, North America, Europe and Argentina in 1991, and Australia in 1992. The launch price was $150 US and £145 UK. Sega dropped support for the Game Gear in early 1997.' },
        'gb': { color: '#414f8b', vendor: 'Nintendo', year: '1989', summary: 'The Game Boy, is an 8-bit handheld video game device developed and manufactured by Nintendo. It was released in Japan on April 21, 1989, in North America in August 1989, and in Europe on September 28, 1990. It is the first handheld console in the Game Boy line, and was created by Gunpei Yokoi and Nintendo Research & Development 1—the same staff who had designed the Game & Watch series as well as several popular games for the Nintendo Entertainment System.' },
        'gba': { color: '#4e73d7', vendor: 'Nintendo', year: '2001', summary: 'The Game Boy Advance, (often shortened to GBA) is a 32-bit handheld video game console developed, manufactured, and marketed by Nintendo. It is the successor to the Game Boy Color. It was released in Japan on March 21, 2001; in North America on June 11, 2001; in Australia and Europe on June 22, 2001; and in the Peoples Republic of China on June 8, 2004 (excluding Hong Kong).' },
        'gbc': { color: '#f5b72c', vendor: 'Nintendo', year: '1998', summary: 'The Game Boy Color is Nintendos successor to the 8-bit Game Boy handheld game console, and was released on October 21, 1998 in Japan, November 19, 1998 in North America, November 23, 1998 in Europe and November 27, 1998 in the United Kingdom. It features a color screen and is slightly thicker and taller than the Game Boy Pocket. As with the original Game Boy, it has an 8-bit processor. The Game Boy and Game Boy Color combined have sold 118.69 million units worldwide.' },
        'genesis': { color: '#c23b2c', vendor: 'Sega', year: '1988', summary: 'The Sega Genesis is a fourth-generation video game console developed and produced by Sega. It was originally released in Japan in 1988 as Mega Drive, then in North America in 1989 as Sega Genesis, and in Europe, Australia and other PAL regions in 1990 as Mega Drive. The reason for the two names is that Sega was unable to secure legal rights to the Mega Drive name in North America. The Sega Genesis is Segas third console and the successor to the Sega Master System with which it has backward compatibility. The controversy over games like Mortal Kombat in the United States forced Sega to create the first content rating system for video games, the Videogame Rating Council, rather than have the games heavily censored. The rating system allowed Sega to ship games with little to no censorship and gave it a competive edge when the same game was released by Nintendo. The success of those games eventually forced Nintendo to join its rating system.' },
        'gw': { color: '#8ea5ae', vendor: 'Nintendo', year: '1980', summary: 'Game & Watch is a line of handheld electronic games produced by Nintendo from 1980 to 1991. Created by game designer Gunpei Yokoi, each Game & Watch features a single game to be played on an LCD screen in addition to a clock, an alarm, or both. It was the earliest Nintendo product to garner major success.There were 59 different Game & Watch games produced for sale and one that was only available as a contest prize, making 60 in all. The prize game was given to winners of Nintendos F-1 Grand Prix tournament, a yellow-cased version of Super Mario Bros. that came in a plastic box modeled after the Disk-kun character Nintendo used to advertise their Famicom Disk System. As only 10,000 units were produced and it was never available for retail sale, the yellow version is considered rare.' },
        'intellivision': { color: '#f28311', vendor: 'Mattel', year: '1979', summary: 'The Intellivision is a video game console released by Mattel in 1979. Development of the console began in 1978, less than a year after the introduction of its main competitor, the Atari 2600. The word intellivision is a portmanteau of "intelligent television". Over 3 million Intellivision units were sold and a total of 125 games were released for the console.' },
        'mame': { color: '#082f72', image: 'arcade' },
        'mastersystem': { color: '#c2403e', vendor: 'Sega', year: '1985', summary: 'The Master System (abbreviated to SMS) is a third-generation video game console that was manufactured and released by Sega in 1985 in Japan (as the Sega Mark III), 1986 in North America and 1987 in Europe. The original SMS could play both cartridges and the credit card-sized "Sega Cards," which retailed for cheaper prices than cartridges but had less code. The SMS also featured accessories such as a light gun and 3D glasses which were designed to work with a range of specially coded games. The Master System was released as a direct competitor to the Nintendo Entertainment System in the third videogame generation The SMS was technically superior to the NES, which predated its release significantly, but failed to overturn Nintendos significant market share advantage in Japan and North America.' },
        'msx': { color: '#32a8ec', vendor: 'Microsoft', year: '1983', summary: 'MSX is a standardized home computer architecture Despite Microsofts involvement, the MSX-based machines were seldom released in the United States, but were popular in Asian countries like Japan and South Korea, South American countries like Brazil and Chile, and in the European market in countries like the Netherlands, France, Spain and Finland. To a lesser extent, the MSX platform was also popular in the former Soviet Union and Kuwait. Before the appearance and great success of Nintendos Family Computer, MSX was the platform for which major Japanese game studios, such as Konami and Hudson Soft, produced video game titles. The Metal Gear series, for example, was originally written for MSX hardware.' },
        'mvs': { color: '#d64444', vendor: 'SNK', year: '1990', summary: 'The Neo Geo originally launched as the Multi Video System (MVS) coin-operated arcade machine. With its games stored on self-contained cartridges, a game cabinet can easily be changed to a different game title by swapping the games cartridge and cabinet artwork. The MVS offers owners the ability to put up to six different cartridges into a single cabinet. This unique feature was a key economic consideration for operators with limited floorspace, as well as saving money long term.'},
        'n64': { color: '#1bb861', vendor: 'Nintendo', year: '1996', summary: 'The Nintendo 64, often referred to as N64, was Nintendos third home video game console for the international market. Named for its 64-bit CPU, it was released in June 1996 in Japan, September 1996 in North America, March 1997 in Europe and Australia, September 1997 in France and December 1997 in Brazil. It is Nintendos last home console to use ROM cartridges to store games (Nintendo switched to a MiniDVD-based format for the successor GameCube); handhelds in the Game Boy line, however, continued to use Game Paks. It was discontinued in 2001 in Japan, North America and PAL regions by the launch of Nintendos GameCube.' },
        'naomi': { color: '#ef8310', vendor: 'Sega', year: '1998', summary: 'The NAOMI (New Arcade Operation Machine Idea) is an arcade system released by Sega in 1998. It was designed as a successor to Sega Model 3 hardware, using a similar architecture to the Sega Dreamcast. The NAOMI was succeeded by the Sega Hikaru and Sega NAOMI 2 boards, though having out-lasted the NAOMI 2, Hikaru and Sega System SP. The Sega Chihiro, or possibly even the Sega Lindbergh, could also be seen as successors.' },
        'nds': { color: '#b6c9d6', vendor: 'Nintendo', year: '2004', summary: 'The Nintendo DS (abbreviated to DS or NDS) is a portable game console produced by Nintendo, first released on November 21, 2004. A distinctive feature of the system is the presence of two separate LCD screens, the lower of which is a touchscreen, encompassed within a clamshell design, similar to the Game Boy Advance SP. The Nintendo DS also features a built-in microphone and supports wireless standards, allowing players to interact with each other within short range, or online with the Nintendo Wi-Fi Connection service. The Nintendo DS is the first Nintendo console to be released in North America before Japan.' },
        'neogeo': { color: '#7c828c', vendor: 'SNK', year: '1990', summary: 'The NeoGeo is a cartridge-based arcade and home video game system released on July 1, 1991 by Japanese game company SNK. Being in the Fourth generation of Gaming, it was the first console in the former Neo Geo family, which only lived through the 1990s. The hardware featured comparatively colourful 2D graphics. The MVS (Multi Video System), as the Neo Geo was known to the coin-op industry, offered arcade operators the ability to put up to 6 different arcade titles into a single cabinet, a key economic consideration for operators with limited floorspace. With its games stored on self-contained cartridges, a game-cabinet could be exchanged for a different game-title by swapping the games ROM-cartridge and cabinet artwork. Several popular franchise-series, including Fatal Fury, The King of Fighters, Metal Slug and Samurai Shodown, were released for the platform. The Neo Geo system was also marketed as a very costly home console, commonly referred to today as the AES (Advanced Entertainment System). The Neo Geo was marketed as 24-bit, though it was technically a parallel processing 16-bit system with an 8-bit Zilog Z80 as coprocessor. The coprocessor was used as a CPU, and for sound processing. The Super Nintendo and Sega Genesis also had similar co-processors, with neither Sega nor Nintendo claiming they were 24-bit.' },
        'neogeocd': { color: '#af98e6', vendor: 'SNK', year: '1994', summary: 'Neo Geo CD is the second home video game console of SNK Corporations Neo Geo family, released in September 1994, four years after its cartridge-based equivalent. This is the same platform, converted to the cheaper CD format retailing at $49 to $79 per title, compared to the $300 cartridges. The system was originally priced at US$399,[2] or £399 in the UK. The units 1X CD-ROM drive is slow, with very long loading times of up to 56 Mbit of data per load.[citation needed] The system can also play Audio CDs. All three versions of the system have no region-lock. The Neo Geo CD was launched bundled with a control pad instead of a joystick like the AES version. However, the original AES joystick can be used with all three Neo Geo CD models. As of March 1997, the Neo Geo CD had sold 570,000 units worldwide'},
        'nes': { color: '#ba3141', vendor: 'Nintendo', year: '1983', summary: 'The Nintendo Entertainment System (also abbreviated as NES or simply called Nintendo) is an 8-bit video game console that was released by Nintendo in North America during 1985, in Europe during 1986 and Australia in 1987. In most of Asia, including Japan (where it was first launched in 1983), China, Vietnam, Singapore, the Middle East and Hong Kong, it was released as the Family Computer, commonly shortened as either the romanized contraction Famicom, or abbreviated to FC. In South Korea, it was known as the Hyundai Comboy, and was distributed by Hynix which then was known as Hyundai Electronics. As the best-selling gaming console of its time, the NES helped revitalize the US video game industry following the video game crash of 1983, and set the standard for subsequent consoles of its generation. With the NES, Nintendo introduced a now-standard business model of licensing third-party developers, authorizing them to produce and distribute software for Nintendos platform.' },
        'ngp': { color: '#ed9f46', vendor: 'SNK', year: '1998', summary: 'The Neo Geo Pocket is a monochrome handheld video game console released by SNK. It was the companys first handheld system and is part of the Neo Geo family. It debuted in Japan in late 1998, however never saw a western release, being exclusive to Japan and smaller Asian markets such as Hong Kong.' },
        'ngpc': { color: '#ed9f46', vendor: 'SNK', year: '1999', summary: 'The Neo Geo Pocket Color (shortened NGPC), is a 16-bit colour handheld video game console manufactured by SNK. It is a successor to SNKs monochrome Neo Geo Pocket handheld which debuted in 1998 in Japan. The Neo Geo Pocket Color was released on March 16, 1999 in Japan, August 6, 1999 in North America, and some time in 1999 in Europe. The Neo Geo Pocket Color was SNKs last video game console, and is backwards compatible with the Neo Geo Pocket. In 2000, following SNKs purchase by American pachinko manufacturer Aruze, the Neo Geo Pocket Color was dropped from both the North American and European markets. It did, however, last until 2001 in Japan, with a total of 2 million units sold.' },
        'odyssey2': { color: '#f08211', vendor: 'Magnavox', year: '1978', summary: 'The Magnavox Odyssey², known in Europe as the Videopac, in Brazil as the Philips Odyssey, in the United States as the Magnavox Odyssey² and the Philips Odyssey², and also by many other names, is a video game console released in 1978. In the early 1970s, Magnavox was an innovator in the home video game industry. They succeeded in bringing the first home video game system to market, the Odyssey, which was quickly followed by a number of later models, each with a few technological improvements (Magnavox Odyssey Series). In 1978, Magnavox, now a subsidiary of North American Philips, released the Odyssey², its new second-generation video game console. In 2009, the video game website IGN named the Odyssey² the 21st greatest video game console, out of its list of 25.' },
        'pcecd': { color: '#598dca', vendor: 'NEC', year: '1988', summary: 'The PC Engine CD-ROM² add-on was released in Japan for the PC Engine console in December of 1988. The North American version, known as the TurboGrafx-CD, went on sale in 1989 for the TurboGrafx-16 (the North American version of the PC Engine). While it had little success in North America, the device boosted sales for the PC Engine in Japan. It helped the PC Engine outsell the NES for a while (up until the release of the SNES) and become the second best-selling console of the 16-bit era, behind the Super Famicom (which later planned its own PlayStation CD add-on) and ahead of the Sega Mega Drive (which later had its own CD-ROM add-on, the Sega CD).' },
        'pcengine': { color: '#bd3e43', vendor: 'NEC', year: '1987', summary: 'TurboGrafx-16, fully titled as TurboGrafx-16 Entertainment SuperSystem and known in Japan as the PC Engine, is a video game console developed by Hudson Soft and NEC, released in Japan on October 30, 1987, and in North America on August 29, 1989.' },
        'pico8': { color: '#1c542d', vendor: 'Lexaloffle', year: '2015', summary: 'PICO-8 is a virtual machine and game engine created by Lexaloffle Games. It is a fantasy video game console that mimics the limited graphical and sound capabilities of 8-bit systems of the 1980s to encourage creativity and ingenuity in producing games without being overwhelmed with the many possibilities of modern tools and machines. Such limitations also give PICO-8 games a particular look and feel.' },
        'pokemini': { color: '#405189', vendor: 'Nintendo', year: '2001', summary: 'The Pokémon Mini is a handheld game console that was designed and manufactured by Nintendo and themed around the Pokémon media franchise. It is the smallest game system with interchangeable cartridges ever produced by Nintendo, weighing just under two and a half ounces (70 grams). It was first released in North America on November 16, 2001, then in Japan on December 14, 2001, and in Europe on March 15, 2002. The systems were released in three colors: Wooper Blue, Chikorita Green, and Smoochum Purple.' },
        'ports': { color: '#1d334a' },
        'ps2': { color: '#3069c0', vendor: 'Sony', year: '2000', summary: 'The PlayStation 2, (officially abbreviated PS2) is a sixth-generation video game console manufactured by Sony as part of the PlayStation series. Its development was announced in March 1999 and it was first released on March 4, 2000, in Japan. Its primary competitors were Segas Dreamcast, Microsofts Xbox, and Nintendos GameCube. The PS2 is the best-selling console of all time, having reached over 150 million units sold as of January 31, 2011.' },
        'psp': { color: '#376da9', vendor: 'Sony', year: '2004', summary: 'The PlayStation Portable, officially abbreviated PSP, is a handheld game console manufactured and marketed by Sony Corporation. The PlayStation Portable is the first and only handheld video game console to use an optical disc format, Universal Media Disc (UMD), as its primary storage medium.' },
        'psx': { color: '#878c92', vendor: 'Sony', year: '1994', summary: 'The PlayStation , officially abbreviated as PS; unofficially referred to as the PSX or PS1) is a 32-bit fifth-generation video game console first released by Sony Computer Entertainment in Japan on December 3, 1994. The PlayStation was the first of the PlayStation series of consoles and handheld game devices. The PlayStation 2 was the consoles successor in 2000. The PlayStation was the first "computer entertainment platform" to ship 100 million units, which it had reached 9 years and 6 months after its initial launch. In 2000, a re-designed, "slim" version was released, called the PSone. This marked the end of the original grey console.' },
        'recents': { color: '#906226', vendor: 'past 30 days' },
        'saturn': { color: '#5b7ada', vendor: 'Sega', year: '1994', summary: 'The Sega Saturn is a 32-bit fifth-generation video game console that was first released by Sega on November 22, 1994 in Japan, May 11, 1995 in North America, and July 8, 1995 in Europe. The system was discontinued in North America and Europe in 1998, and in 2000 in Japan. While it was popular in Japan, the Saturn failed to gain a similar market share in North America and Europe against its main competitors: Sonys PlayStation and the Nintendo 64.' },
        'scummvm': { color: '#f09514', vendor: 'Lucasfilm Games', year: '1987', summary: 'Script Creation Utility for Maniac Mansion Virtual Machine (ScummVM) is a set of game engine recreations. Originally designed to play LucasArts adventure games that use the SCUMM system, it also supports a variety of non-SCUMM games by companies like Revolution Software and Adventure Soft.' },
        'sega32x': { color: '#0e7acd', vendor: 'Sega', year: '1994', summary: 'The Sega 32X, codenamed Project Mars, is an add-on for the Mega Drive/Genesis video game console by Sega. Its aim was to increase the lifespan of the aging Mega Drive/Genesis system, which was facing stiff competition from the SNES. While connecting it to Mega Drive did increase its capabilities, reluctance to adapt due to the previous failure of the Mega-CD and the upcoming Sega Saturn system led to low sales and a short lifespan. It was distributed under the name Sega Super 32X in Japan, Sega Genesis 32X in North America, Sega Mega Drive 32X in the PAL region, and Sega Mega 32X in Brazil.' },
        'segacd': { color: '#0e7acd', vendor: 'Sega', year: '1991', summary: 'The Mega-CD is an add-on device for the Mega Drive video game console, designed and produced by Sega and released in Japan, Europe, Australia, New Zealand, and South Africa. The device was also released in North America under the name Sega CD, for the Sega Genesis. The device adds a CD-ROM drive to the console, allowing the user to play CD-based games and providing additional hardware functionality. It can also play audio CDs and CD+G discs. The development of the Mega-CD was confidential; game developers were not made aware of what exactly they were working on until the add-on was finally revealed at the Tokyo Toy Show in Japan. The Mega-CD was designed to compete with the PC Engine CD (TurboGrafx-16 CD) in Japan, which had a separate CD-ROM drive. The first version of the Mega-CD sits underneath the Mega Drive console and loads CDs via a motorized tray. A second version places a top-loading CD-ROM drive to the right of the console and is intended primarily for use with the redesigned Sega Mega Drive 2. Both versions of the Mega-CD are compatible with the initial two versions of the Mega Drive console, but not with the Mega Drive 3 or Genesis 3.' },
        'sfc': { color: '#ecb83b', vendor: 'Nintendo', year: '1990', summary: 'The Super Nintendo Entertainment System (also known as the Super NES, SNES or Super Nintendo) is a 16-bit video game console that was released by Nintendo in North America, Europe, Australasia (Oceania), and South America between 1990 and 1993. In Japan and Southeast Asia, the system is called the Super Famicom (officially adopting the abbreviated name of its predecessor, the Family Computer), or SFC for short. In South Korea, it is known as the Super Comboy and was distributed by Hyundai Electronics. Although each version is essentially the same, several forms of regional lockout prevent the different versions from being compatible with one another. The Super Nintendo Entertainment System was Nintendos second home console, following the Nintendo Entertainment System (NES). The console introduced advanced graphics and sound capabilities compared with other consoles at the time. Additionally, development of a variety of enhancement chips (which were integrated on game circuit boards) helped to keep it competitive in the marketplace. The SNES was a global success, becoming the best-selling console of the 16-bit era despite its relatively late start and the fierce competition it faced in North America and Europe from Segas Genesis console. The SNES remained popular well into the 32-bit era, and although Nintendo no longer offers factory repairs/replacement or accessories for the console, it continues to be popular among fans, collectors, retro gamers, and emulation enthusiasts, some of whom are still making homebrew ROM images.' },
        'sg1000': { color: '#0c8427', vendor: 'Sega', year: '1983', summary: 'The SG-1000 is a cartridge-based home video game console manufactured by Sega and released in Japan, Australia, and other countries. This system marked Segas first entry into the home video game hardware business, and provided the basis for the more successful Master System. The SG-1000s game library comprises 68 standard cartridge releases and 29 Sega Card releases. All of the SG-1000s games play on each model of the console, though 26 of the cartridge releases require the attached keyboard accessory or the SC-3000. In addition, all titles are fully compatible with the Mark III and Master System. Titles for the system include Flicky, Congo Bongo, Sega-Galaga, and Girls Garden, the first video game directed by Sonic the Hedgehog creator Yuji Naka. The game library for the SG-1000 also included licensed titles, such as Golgo 13.' },
        'snes': { color: '#d64042', vendor: 'Nintendo', year: '1990', summary: 'The Super Nintendo Entertainment System (also known as the Super NES, SNES or Super Nintendo) is a 16-bit video game console that was released by Nintendo in North America, Europe, Australasia (Oceania), and South America between 1990 and 1993. In Japan and Southeast Asia, the system is called the Super Famicom (officially adopting the abbreviated name of its predecessor, the Family Computer), or SFC for short. In South Korea, it is known as the Super Comboy and was distributed by Hyundai Electronics. Although each version is essentially the same, several forms of regional lockout prevent the different versions from being compatible with one another. The Super Nintendo Entertainment System was Nintendos second home console, following the Nintendo Entertainment System (NES). The console introduced advanced graphics and sound capabilities compared with other consoles at the time. Additionally, development of a variety of enhancement chips (which were integrated on game circuit boards) helped to keep it competitive in the marketplace. The SNES was a global success, becoming the best-selling console of the 16-bit era despite its relatively late start and the fierce competition it faced in North America and Europe from Segas Genesis console. The SNES remained popular well into the 32-bit era, and although Nintendo no longer offers factory repairs/replacement or accessories for the console, it continues to be popular among fans, collectors, retro gamers, and emulation enthusiasts, some of whom are still making homebrew ROM images.' },
        'supergrafx': { color: '#69b5dc', vendor: 'NEC', year: '1989', summary: 'The PC Engine SuperGrafx, also known as simply the SuperGrafx, is a fourth-generation home video game console manufactured by NEC Home Electronics and released in Japan in 1989. It is the successor system to the PC Engine, released two years prior. Originally known as the PC Engine 2 during production stages, it was purported as a true 16-bit home console, featuring improved graphics and audio capabilities over its predecessor. The console was rushed to market, released several months before its initial intended release date in 1990, only having modest updates to the hardware. With only six retail games released that took advantage of the consoles hardware updates, the SuperGrafx was a commercial failure, selling only 75,000 units total. None of the hardware advancements it possessed were carried over to later PC Engine models, such as the Duo.' },
        'switch': { color: '#fb584f', vendor: 'Nintendo', year: '2017', summary: 'The Nintendo Switch, is Nintendos seventh major home console. Originally known in development as the NX, it was officially unveiled in October 2016 and released worldwide on March 3, 2017. The Switch is a "hybrid" console, allowing different modes of play. Its main unit is shaped like a tablet computer which can be used portably as-is, or connected to a television display through a detachable docking station. In addition it can also be used in a tapletop form with its kickstand. Despite these characteristics, Nintendo markets the Switch primarily as a home console rather than as a portable. Its most distinguishable feature are the "Joy-Con" controllers. These are two detachable controllers that can be either attached to a "Grip" to provide a traditional home console gamepad form, attached on either side of the main unit for handheld play, or can be used individually in the hand like Nintendos Wii Remote. The Joy-Cons are similarly motion-sensitive, and feature NFC for reading Amiibo data. The Switch uses flash ROM cartridges for media, rather than optical discs.' },
        'tg16': { color: '#f3994d', vendor: 'NEC', year: '1987', summary: 'TurboGrafx-16, fully titled as TurboGrafx-16 Entertainment SuperSystem and known in Japan as the PC Engine, is a video game console developed by Hudson Soft and NEC, released in Japan on October 30, 1987, and in North America on August 29, 1989.' },
        'tgcd': { color: '#340f7a', vendor: 'NEC', year: '1988', summary: 'The PC Engine CD-ROM² add-on was released in Japan for the PC Engine console in December of 1988. The North American version, known as the TurboGrafx-CD, went on sale in 1989 for the TurboGrafx-16 (the North American version of the PC Engine). While it had little success in North America, the device boosted sales for the PC Engine in Japan. It helped the PC Engine outsell the NES for a while (up until the release of the SNES) and become the second best-selling console of the 16-bit era, behind the Super Famicom (which later planned its own PlayStation CD add-on) and ahead of the Sega Mega Drive (which later had its own CD-ROM add-on, the Sega CD).' },
        'vboy': { color: '#e3414c', vendor: 'Nintendo', year: '1995', summary: 'The Virtual Boy was a table-top video game console developed and manufactured by Nintendo. It was the first video game console that was supposed to be capable of displaying "true 3D graphics" out of the box, in a form of virtual reality. Whereas most video games use monocular cues to achieve the illusion of three dimensions on a two-dimensional screen, The Virtual Boy creates an illusion of depth through the effect known as parallax. In a manner similar to using a head-mounted display, the user looks into an eyepiece made of neoprene on the front of the machine, and then an eyeglass-style projector allows viewing of the monochromatic (in this case, red) image. It was released on July 21, 1995 in Japan and August 14, 1995 in North America at a price of around US$180. It then became a commercial failure and it was not released in PAL markets. It met with a lukewarm reception that was unaffected by continued price drops. Nintendo discontinued it the following year.' },
        'vectrex': { color: '#4f97d9', vendor: 'Milton Bradley', year: '1982', summary: 'The Vectrex is a vector display-based home video game console that was developed by Western Technologies/Smith Engineering. It was licensed and distributed first by General Consumer Electronics (GCE), and then by Milton Bradley Company after its purchase of GCE. Unlike other non-portable video game consoles, which connected to televisions and rendered raster graphics, the Vectrex has an integrated vector monitor which displays vector graphics. The Vectrex is monochrome and uses plastic screen overlays to simulate color and various static graphics and decorations. At the time, many of the most popular arcade games used vector displays, and through a licensing deal with Cinematronics, GCE was able to produce high-quality versions of arcade games such as Space Wars and Armor Attack.' },
        'vita': { color: '#0162c2', vendor: 'Sony', year: '2011', summary: 'The PlayStation Vita is a handheld game console manufactured and marketed by Sony Computer Entertainment. It is the successor to the PlayStation Portable as part of the PlayStation brand of gaming devices. The handheld includes two analog sticks, a 5-inch (130 mm) OLED multi-touch capacitive touchscreen, and supports Bluetooth, Wi-Fi and optional 3G.' },
        'wii': { color: '#81cceb', vendor: 'Nintendo', year: '2006', summary: 'The Wii is a home video game console released by Nintendo on November 19, 2006. As a seventh-generation console, the Wii primarily competes with Microsofts Xbox 360 and Sonys PlayStation 3. Nintendo states that its console targets a broader demographic than that of the two others. As of November 2011, the Wii leads the generation over the PlayStation 3 and Xbox 360 in worldwide sales, and in December 2009 broke the record for best-selling console in a single month in the United States. A distinguishing feature of the console is its wireless controller, the Wii Remote, which can be used as a handheld pointing device and detects movement in three dimensions. Another distinctive feature of the console is WiiConnect24, which enables it to receive messages and updates over the Internet while in standby mode. The Wii is Nintendos fifth home console and the direct successor of the Nintendo GameCube, being fully backwardly compatible with all GameCube games and most accessories.' },
        'wswan': { color: '#77cbbd', vendor: 'Bandai', year: '1999', summary: 'The WonderSwan was a line of handheld game consoles produced in Japan by Bandai. It was developed by Gunpei Yokois company Koto and Bandai. The WonderSwan was made to compete with the Neo Geo Pocket Color and the market leader Nintendos Game Boy Color (even though the developer for the WonderSwan, Gunpei Yokoi, developed the original Nintendo Game Boy). The original WonderSwan was later replaced by the WonderSwan Color; although some WonderSwan Color games are compatible with the original WonderSwan, many are designed exclusively for the WonderSwan Color and show a message such as "This cartridge is for WonderSwan Color only" when run on the original WonderSwan. The WonderSwan is playable both vertically and horizontally, and feature a fairly large library of games, including numerous first-party titles based on licensed anime properties, with significant third-party support from Square and Capcom. As it was a console designed essentially for the Japanese market, most of the games are in Japanese, with only a few featuring English text.' },
        'wswanc': { color: '#42b1e6', vendor: 'Bandai', year: '1999', summary: 'The WonderSwan Color was released on December 9, 2000 in Japan, and was a moderate success. The original WonderSwan had only a black and white screen. Although the WonderSwan Color was slightly larger and heavier (7 mm and 2 g) compared to the original WonderSwan, the color version featured 512KB of RAM and a larger color LCD screen. In addition, the WonderSwan Color is compatible with the original WonderSwan library of games. Prior to WonderSwans release, Nintendo had a virtual monopoly in the Japanese video game handheld market. After the release of the WonderSwan Color, Bandai took approximately 8% of the market share in Japan partly due to its low price of ¥6800 Japanese yen (approximately $59 USD). Another reason for the WonderSwans success in Japan was the fact that Bandai managed to get a deal with Square to port over the original Famicom Final Fantasy games with improved graphics and controls. However, with the popularity of the Game Boy Advance and the reconciliation between Square and Nintendo, the WonderSwan Color and its successor, the SwanCrystal, quickly lost its competitive advantage.' },
        'x68000': { color: '#6b6d71', vendor: 'Sharp', year: '1987', summary: 'The X68000 is a home computer created by Sharp Corporation, first released in 1987, sold only in Japan. In terms of hardware, it is very similar to arcade machines of the time, and serves as the Capcom CPS system development machine. It supports separate text RAM, graphic RAM and hardware sprites. Sound is produced internally via Yamahas then top-of-the-line YM2151 FM synthesizer and a single channel OKI MSM6258V for PCM. Due to this and other similarities, it played host to many arcade game ports in its day. Games made for this system include Parodius Da! －Shinwa kara Owarai e－, Ghouls n Ghosts, Strider, Final Fight, Alien Syndrome, Street Fighter II Dash, Akumajo Dracula (Castlevania in other regions, the X68000 version was ported to the PlayStation as Castlevania Chronicles), Cho Ren Sha 68k (which has a Windows port) and many others. Many games also supported the Roland SC-55 and MT-32 MIDI modules for sound as well as mixed-mode internal/external output.' },
        'zxspectrum': { color: '#9a2611', vendor: 'Sinclair', year: '1982', summary: 'The ZX Spectrum (pronounced "Zed-Ex") is an 8-bit personal home computer released in the United Kingdom in 1982 by Sinclair Research Ltd. Referred to during development as the ZX81 Colour and ZX82, the machine was launched as the ZX Spectrum by Sinclair to highlight the machines colour display, compared with the black-and-white of its predecessor, the ZX81. The Spectrum was ultimately released as eight different models, ranging from the entry level model with 16 kB RAM released in 1982 to the ZX Spectrum +3 with 128 kB RAM and built in floppy disk drive in 1987; together they sold in excess of 5 million units worldwide (not counting numerous clones). The Spectrum was among the first mainstream audience home computers in the UK, similar in significance to the Commodore 64 in the USA. The introduction of the ZX Spectrum led to a boom in companies producing software and hardware for the machine, the effects of which are still seen; some credit it as the machine which launched the UK IT industry. Licensing deals and clones followed, and earned Clive Sinclair a knighthood for "services to British industry". The Commodore 64, BBC Microcomputer and later the Amstrad CPC range were major rivals to the Spectrum in the UK market during the early 1980s. Over 24,000 software titles have been released since the Spectrums launch and new titles continue to be released, with over 90 new ones in 2010.' },
    };
}
